server:
  port: 7337

spring:
  application:
    name: authorization_service
  datasource:
    url: jdbc:postgresql://localhost:5432/sd_authorization_db
    username: postgres
    password: lumia640
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
